import {NgModule, Pipe, PipeTransform} from '@angular/core';
import { CommonModule } from '@angular/common';
import {MatExpansionModule} from '@angular/material/expansion';
import {MatCardModule} from '@angular/material/card';
import {
  AddingandSubtractingFractions,
  AddingandSubtractingSquareRoots,
  AddingIntegers,
  AnIntroductiontoExponentiation,
  AnIntroductiontoExponentRules,
  AnIntroductiontoFunctions,
  AnIntroductiontoLinearEquations,
  AnintroductiontoPolynomails,
  AnIntroductiontoRoots,
  AnIntroductiontoWordProblems,
  ApplyingPowers,
  ApplyingQuadraticFunctions,
  ApplyingRoots,
  ApplyingtheOrderofOperations,
  AProductPropertyforSquareRoots,
  BeginningPolynomialFactoring,
  BeginningPolynomialMultiplication,
  ConcludingLinearEquations,
  ContinuingPolynomialFactoring,
  ContinuingwithExponentRules,
  ContinuingwithLinearEquations,
  ContinuingwithPolynomialMultiplication,
  ContinuingwithWordProblems,
  FactoringMultivariatePolynomials,
  Intercepts,
  LinearFunctionsinSlopeInterceptForm,
  MultiplyingandDividingFractions,
  MultiplyingandDividingIntegers,
  OperationswithMultivariatePolynomials,
  OtherLinearFunctionTopics,
  PolynomialPrimeFactorization,
  PreparingforLinearEquationsPart1,
  PreparingforLinearEquationsPart2,
  PreparingfortheQuadraticFormula,
  QuadraticFunctionsinStandardForm,
  QuotientsandSquareRoots,
  ReducingFractions,
  RewritingLinearFunctionsIntoSlopeInterceptForm,
  ScientificNotation,
  SolvingLinearInequalities,
  SubtractingIntegers,
  TheOrderofOperations,
  TheQuadraticFormula, TheSlopeofaLinearFunction, TheSolutionSetforaLinearInequality, TheSquareRootMethod, TheZeroProductMethod
} from './pages.component';
import {MatVideoModule} from 'mat-video';
import {BrowserAnimationsModule} from '@angular/platform-browser/animations';


@NgModule({
  declarations: [AddingandSubtractingFractions,
    AddingandSubtractingSquareRoots,
    AddingIntegers,
    AnIntroductiontoExponentiation,
    AnIntroductiontoExponentRules,
    AnIntroductiontoFunctions,
    AnIntroductiontoLinearEquations,
    AnintroductiontoPolynomails,
    AnIntroductiontoRoots,
    AnIntroductiontoWordProblems,
    ApplyingPowers,
    ApplyingQuadraticFunctions,
    ApplyingRoots,
    ApplyingtheOrderofOperations,
    AProductPropertyforSquareRoots,
    BeginningPolynomialFactoring,
    BeginningPolynomialMultiplication,
    ConcludingLinearEquations,
    ContinuingPolynomialFactoring,
    ContinuingwithExponentRules,
    ContinuingwithLinearEquations,
    ContinuingwithPolynomialMultiplication,
    ContinuingwithWordProblems,
    FactoringMultivariatePolynomials,
    Intercepts, LinearFunctionsinSlopeInterceptForm,
    MultiplyingandDividingFractions,
    MultiplyingandDividingIntegers,
    OperationswithMultivariatePolynomials,
    OtherLinearFunctionTopics,
    PolynomialPrimeFactorization,
    PreparingforLinearEquationsPart1,
    PreparingforLinearEquationsPart2,
    PreparingfortheQuadraticFormula,
    QuadraticFunctionsinStandardForm,
    QuotientsandSquareRoots,
    ReducingFractions, RewritingLinearFunctionsIntoSlopeInterceptForm,
    ScientificNotation,
    SolvingLinearInequalities,
    SubtractingIntegers,
    TheOrderofOperations,
    TheQuadraticFormula,
    TheSlopeofaLinearFunction,
    TheSolutionSetforaLinearInequality,
    TheSquareRootMethod, TheZeroProductMethod,
  ],
  imports: [
    CommonModule,
    MatExpansionModule,
    MatCardModule,
    BrowserAnimationsModule,
    MatVideoModule
  ],
  exports: [
    SubtractingIntegers
  ]
})
export class PagesModule { }

